### ISSUE TITLE
执行python app.py后遇到报错如下，请问应该如何解决？

### ISSUE THREAD

**Issue by hjh0915** [AgentEra/Agently-Daily-News-Collector#17]
Exception in thread Thread-1 (start_in_theard):
Traceback (most recent call last):
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/home/jonna/.pyenv/versions/3.10.12/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/openai/_base_client.py", line 1537, in _request
    response = await self._client.send(
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/home/jonna/.pyenv/versions/3.10.12/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Agent/Agent.py", line 240, in start_in_theard
    reply = loop.run_until_complete(self.start_async(request_type))
  File "/home/jonna/.pyenv/versions/3.10.12/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Agent/Agent.py", line 227, in start_async
    raise(e)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Agent/Agent.py", line 177, in start_async
    event_generator = await self.request.get_event_generator(request_type)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Request/Request.py", line 116, in get_event_generator
    response_generator = await request_plugin_export["request_model"](request_data)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/plugins/request/OAIClient.py", line 208, in request_model
    stream = await client.chat.completions.create(**request_data)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1283, in create
    return await self._post(
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/openai/_base_client.py", line 1805, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/openai/_base_client.py", line 1503, in request
    return await self._request(
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/openai/_base_client.py", line 1546, in _request
    return await self._retry_request(
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/openai/_base_client.py", line 1546, in _request
    return await self._retry_request(
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/openai/_base_client.py", line 1556, in _request
    raise APITimeoutError(request=request) from err
openai.APITimeoutError: Request timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonna/.pyenv/versions/3.10.12/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/jonna/.pyenv/versions/3.10.12/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Agent/Agent.py", line 243, in start_in_theard
    raise Exception(f"[Agent Request] Error: { str(e) }")
Exception: [Agent Request] Error: Request timed out.
2024-06-20 09:52:50,025	[INFO]	[Outline Generated]	None
2024-06-20 09:52:55,029 - ERROR - Node Execution Exception-'generate_columns'(bca2f28a-fd02-4aa5-9dfc-fcb4057db725):
 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 336, in _exec_chunk_with_dep_core
    exec_res = chunk_executor(input_value, self.store)
  File "/home/jonna/Agently-Daily-News-Collector/workflows/main_workflow.py", line 52, in generate_columns_executor
    for column_outline in outline["column_list"]:
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonna/Agently-Daily-News-Collector/app.py", line 21, in <module>
    main_workflow.start(
  File "/home/jonna/Agently-Daily-News-Collector/workflows/main_workflow.py", line 101, in start
    main_workflow.start()
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Workflow/Workflow.py", line 78, in start
    res = asyncio.run(self.start_async(start_data))
  File "/home/jonna/.pyenv/versions/3.10.12/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/jonna/.pyenv/versions/3.10.12/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Workflow/Workflow.py", line 74, in start_async
    res = await self.executor.start(executed_schema, start_data)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 46, in start
    await self._execute_main(executed_schema.get('entries') or [])
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 101, in _execute_main
    await asyncio.gather(*entry_tasks)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 87, in execute_from_entry
    await self._execute_partial(
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 175, in _execute_partial
    await asyncio.gather(*next_child_tasks)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 146, in _execute_partial
    await execute_child_chunk(next_chunk)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 129, in execute_child_chunk
    child_executed = await self._execute_single_chunk(
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 203, in _execute_single_chunk
    await self._execute_single_chunk_core(
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 230, in _execute_single_chunk_core
    exec_value = await self._exec_chunk_with_dep_core(chunk, single_dep_map)
  File "/home/jonna/.pyenv/versions/py3/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 340, in _exec_chunk_with_dep_core
    raise Exception(e)
Exception: 'NoneType' object is not subscriptable

**Comment by Maplemx** [comment]
Exception: [Agent Request] Error: Request timed out.

Please check your connection to model. If you're firewall blocked, use a proxy and set proxy server host and port into SETTINGS.yaml.
