### ISSUE TITLE
执行app.python后报错

### ISSUE THREAD

**Issue by Bbbnz** [AgentEra/Agently-Daily-News-Collector#19]
Exception in thread Thread-2 (start_in_theard):
Traceback (most recent call last):
  File "D:\App\python\lib\site-packages\Agently\Agent\Agent.py", line 240, in start_in_theard
    reply = loop.run_until_complete(self.start_async(request_type))
  File "D:\App\python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\App\python\lib\site-packages\Agently\Agent\Agent.py", line 227, in start_async
    raise(e)
  File "D:\App\python\lib\site-packages\Agently\Agent\Agent.py", line 177, in start_async
    event_generator = await self.request.get_event_generator(request_type)
  File "D:\App\python\lib\site-packages\Agently\Request\Request.py", line 116, in get_event_generator
    response_generator = await request_plugin_export["request_model"](request_data)
  File "D:\App\python\lib\site-packages\Agently\plugins\request\OAIClient.py", line 208, in request_model
    stream = await client.chat.completions.create(**request_data)
  File "D:\App\python\lib\site-packages\openai\resources\chat\completions.py", line 1289, in create
    return await self._post(
  File "D:\App\python\lib\site-packages\openai\_base_client.py", line 1805, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "D:\App\python\lib\site-packages\openai\_base_client.py", line 1503, in request
    return await self._request(
  File "D:\App\python\lib\site-packages\openai\_base_client.py", line 1599, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: <Input Y*************ere>. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\App\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\App\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\App\python\lib\site-packages\Agently\Agent\Agent.py", line 243, in start_in_theard
    raise Exception(f"[Agent Request] Error: { str(e) }")
Exception: [Agent Request] Error: Error code: 401 - {'error': {'message': 'Incorrect API key provided: <Input Y*************ere>. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
2024-07-01 11:26:26,697 [INFO]  [Outline Generated]     None
2024-07-01 11:26:31,705 - ERROR - Node Execution Exception-'generate_columns'(0c44bfbe-6d36-41e2-aa6f-36725a35d296):
 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\App\python\lib\site-packages\Agently\Workflow\MainExecutor.py", line 338, in _exec_chunk_with_dep_core
    exec_res = chunk_executor(input_value, self.store)
  File "D:\project\News AI agent\Agently-Daily-News-Collector\workflows\main_workflow.py", line 57, in generate_columns_executor
    for column_outline in outline["column_list"]:
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\News AI agent\Agently-Daily-News-Collector\app.py", line 21, in <module>
    main_workflow.start(
  File "D:\project\News AI agent\Agently-Daily-News-Collector\workflows\main_workflow.py", line 109, in start
    main_workflow.start()
  File "D:\App\python\lib\site-packages\Agently\Workflow\Workflow.py", line 114, in start
    return run_async(self.start_async(start_data, storage=storage))
  File "D:\App\python\lib\site-packages\Agently\Workflow\utils\runner.py", line 33, in run_async
    return future.result()
  File "D:\App\python\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "D:\App\python\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\App\python\lib\site-packages\Agently\Workflow\utils\runner.py", line 22, in runner
    result = loop.run_until_complete(coro)
  File "D:\App\python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\App\python\lib\site-packages\Agently\Workflow\Workflow.py", line 110, in start_async
    res = await self.executor.start(executed_schema, start_data, storage=storage)
  File "D:\App\python\lib\site-packages\Agently\Workflow\MainExecutor.py", line 48, in start
    await self._execute_main(executed_schema.get('entries') or [])
  File "D:\App\python\lib\site-packages\Agently\Workflow\MainExecutor.py", line 103, in _execute_main
    await asyncio.gather(*entry_tasks)
  File "D:\App\python\lib\site-packages\Agently\Workflow\MainExecutor.py", line 89, in execute_from_entry
    await self._execute_partial(
  File "D:\App\python\lib\site-packages\Agently\Workflow\MainExecutor.py", line 177, in _execute_partial
    await asyncio.gather(*next_child_tasks)
  File "D:\App\python\lib\site-packages\Agently\Workflow\MainExecutor.py", line 148, in _execute_partial
    await execute_child_chunk(next_chunk)
  File "D:\App\python\lib\site-packages\Agently\Workflow\MainExecutor.py", line 131, in execute_child_chunk
    child_executed = await self._execute_single_chunk(
  File "D:\App\python\lib\site-packages\Agently\Workflow\MainExecutor.py", line 205, in _execute_single_chunk
    await self._execute_single_chunk_core(
  File "D:\App\python\lib\site-packages\Agently\Workflow\MainExecutor.py", line 232, in _execute_single_chunk_core
    exec_value = await self._exec_chunk_with_dep_core(chunk, single_dep_map)
  File "D:\App\python\lib\site-packages\Agently\Workflow\MainExecutor.py", line 342, in _exec_chunk_with_dep_core
    raise Exception(e)
Exception: 'NoneType' object is not subscriptable

**Comment by Maplemx** [comment]
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: <Input Y*************ere>. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
