### ISSUE TITLE
执行app.py后，在执行summarzing时出现报错

### ISSUE THREAD

**Issue by Joecsr24** [AgentEra/Agently-Daily-News-Collector#20]
报错信息如下：

2024-10-10 09:52:35,513 - ERROR - Node Execution Exception-'generate_columns'(generate_columns):
 'MainExecutor' object has no attribute 'store'
Traceback (most recent call last):
  File "E:\Python\Lib\site-packages\Agently\Workflow\MainExecutor.py", line 318, in _exec_chunk_with_dep_core
    exec_res = chunk_executor(input_value, self.runtime_state.user_store)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\github\Agently-Daily-News-Collector\workflows\main_workflow.py", line 59, in generate_columns_executor
    column_data = start_column_workflow(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\github\Agently-Daily-News-Collector\workflows\column_workflow.py", line 172, in start
    return column_workflow.executor.store.get("final_result")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainExecutor' object has no attribute 'store'. Did you mean: 'start'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\github\Agently-Daily-News-Collector\app.py", line 34, in <module>
    main_workflow.start(
  File "E:\github\Agently-Daily-News-Collector\workflows\main_workflow.py", line 110, in start
    main_workflow.start()
  File "E:\Python\Lib\site-packages\Agently\Workflow\Workflow.py", line 155, in start
    return run_async(self.start_async(start_data, storage=storage))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Lib\site-packages\Agently\Workflow\utils\runner.py", line 33, in run_async
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\Python\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "E:\Python\Lib\site-packages\Agently\Workflow\utils\runner.py", line 22, in runner
    result = loop.run_until_complete(coro)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\Python\Lib\site-packages\Agently\Workflow\Workflow.py", line 150, in start_async
    res = await self.executor.start(executed_schema, start_data, storage=storage)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Lib\site-packages\Agently\Workflow\MainExecutor.py", line 57, in start
    await self._execute_main(executed_schema.get('entries') or [])
  File "E:\Python\Lib\site-packages\Agently\Workflow\MainExecutor.py", line 127, in _execute_main
    await asyncio.gather(*entry_tasks)
  File "E:\Python\Lib\site-packages\Agently\Workflow\MainExecutor.py", line 120, in execute_from_entry
    await self._execute_partial(entry, branch_state)
  File "E:\Python\Lib\site-packages\Agently\Workflow\MainExecutor.py", line 151, in _execute_partial
    has_been_executed = await self._execute_single_chunk(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Lib\site-packages\Agently\Workflow\MainExecutor.py", line 197, in _execute_single_chunk
    await self._execute_single_chunk_core(
  File "E:\Python\Lib\site-packages\Agently\Workflow\MainExecutor.py", line 225, in _execute_single_chunk_core
    exec_res = await self._exec_chunk_with_dep_core(chunk, single_dep_map)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Lib\site-packages\Agently\Workflow\MainExecutor.py", line 326, in _exec_chunk_with_dep_core
    raise Exception(e)
Exception: 'MainExecutor' object has no attribute 'store'

**Comment by Maplemx** [comment]
请检查Agently的版本号，回退到3.3.4.7试试

**Comment by Joecsr24** [comment]
> 请检查Agently的版本号，回退到3.3.4.7试试

问题解决，thx
