### ISSUE TITLE
执行app.py文件后报错（'MainExecutor' object has no attribute 'store'）

### ISSUE THREAD

**Issue by WenhaoYao** [AgentEra/Agently-Daily-News-Collector#23]
环境：Agently==3.4.1.1
报错：Exception: 'MainExecutor' object has no attribute 'store'
日志： 'MainExecutor' object has no attribute 'store'
Traceback (most recent call last):
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 318, in _exec_chunk_with_dep_core
    exec_res = chunk_executor(input_value, self.runtime_state.user_store)
  File "/Users/wenhaoyao/Downloads/Agently-Daily-News-Collector-main/workflows/main_workflow.py", line 59, in generate_columns_executor
    column_data = start_column_workflow(
  File "/Users/wenhaoyao/Downloads/Agently-Daily-News-Collector-main/workflows/column_workflow.py", line 172, in start
    return column_workflow.executor.store.get("final_result")
AttributeError: 'MainExecutor' object has no attribute 'store'. Did you mean: 'start'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wenhaoyao/Downloads/Agently-Daily-News-Collector-main/app.py", line 34, in <module>
    main_workflow.start(
  File "/Users/wenhaoyao/Downloads/Agently-Daily-News-Collector-main/workflows/main_workflow.py", line 110, in start
    main_workflow.start()
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/site-packages/Agently/Workflow/Workflow.py", line 155, in start
    return run_async(self.start_async(start_data, storage=storage))
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/site-packages/Agently/Workflow/utils/runner.py", line 33, in run_async
    return future.result()
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/site-packages/Agently/Workflow/utils/runner.py", line 22, in runner
    result = loop.run_until_complete(coro)
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/site-packages/Agently/Workflow/Workflow.py", line 150, in start_async
    res = await self.executor.start(executed_schema, start_data, storage=storage)
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 57, in start
    await self._execute_main(executed_schema.get('entries') or [])
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 127, in _execute_main
    await asyncio.gather(*entry_tasks)
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 120, in execute_from_entry
    await self._execute_partial(entry, branch_state)
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 151, in _execute_partial
    has_been_executed = await self._execute_single_chunk(
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 197, in _execute_single_chunk
    await self._execute_single_chunk_core(
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 225, in _execute_single_chunk_core
    exec_res = await self._exec_chunk_with_dep_core(chunk, single_dep_map)
  File "/Users/wenhaoyao/miniforge3/envs/agently/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 326, in _exec_chunk_with_dep_core
    raise Exception(e)
Exception: 'MainExecutor' object has no attribute 'store'

**Comment by Maplemx** [comment]
这个项目使用的Agently版本是Agently==3.3.4.7，需要手动回退

Agently 3.4版本重构了Workflow的底层
