### ISSUE TITLE
Exception: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by PandaPan123** [AgentEra/Agently-Daily-News-Collector#7]
**我想获取的数据**
```
  report_title: "新能源行业动态"
  column_list:
    - column_title: 新能源汽车
      column_requirement: 最近发布的新能源车企的新车型
      search_keywords: 新能源汽车 新车型 发布
    - column_title: 清洁能源技术
      column_requirement: 最近宣布的清洁能源技术突破
      search_keywords: 清洁能源 技术 突破 公告
    - column_title: 能源政策
      column_requirement: 近期出台的新能源政策和法规
      search_keywords: 新能源 政策 法规 近期
    - column_title: 可再生能源项目
      column_requirement: 最近启动或完成的可再生能源项目
      search_keywords: 可再生能源 项目 启动 完成
    - column_title: 电动汽车充电基础设施
      column_requirement: 最新宣布的电动汽车充电设施建设计划
      search_keywords: 电动汽车 充电设施 建设 计划
```

**错误提示**
```
[Realtime Response]

It seems as if you have posted a piece of news consisting of multiple articles. How may I assist you with this information?
--------------------------

[Final Response]
 It seems as if you have posted a piece of news consisting of multiple articles. How may I assist you with this information?
--------------------------

[Cleaned JSON String]:
 None

--------------------------

Exception in thread Thread-2 (start_in_theard):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Agent/Agent.py", line 236, in start_in_theard
    reply = loop.run_until_complete(self.start_async(request_type))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Agent/Agent.py", line 227, in start_async
    raise(e)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Agent/Agent.py", line 218, in start_async
    raise Exception(reply[14:])
Exception: [Agent Request] Error still occured when try to fix JSON decode error: Empty strings are not legal JSON5
Origin JSON String:
赛力斯"H"评级,目标价131.8元,看涨企业业绩及市值。', 'url': 'https://finance.sina.com.cn/stock/relnews/hk/2024-06-04/doc-iihxzinh5484921.shtml', 'source': '新浪财经', 'date': '2024-06-04T23:00:00+00:00'}]

# [OUTPUT]:
Summary for each news:
1. Company '赛力斯' released 32410 new energy vehicles in May, with a year-on-year growth of 298.62%.
2. Pickup truck scenarios have fundamentally changed and the multi-scene user base will be one of the driving forces for the growth of the pickup truck market in the future.
3. The Ministry of Industry and Information Technology, the Ministry of Finance, and the State Administration of Taxation have recently adjusted the technical requirements for the first energy and new energy automobile products that enjoy vehicle and vessel tax
2024-06-04 15:11:32,980 - ERROR - Node Execution Exception: 'pick_news'(e3337215-a088-42e5-b859-2d3c5749b64f) 'NoneType' object is not iterable
2024-06-04 15:11:32,981 - ERROR - Node Execution Exception: 'generate_columns'(17567005-af95-4b3c-b6ee-bc228f984a50) 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/MainExecutor.py", line 266, in _exec_chunk_with_dep_core
    exec_res = chunk_executor(deps_dict, self.store)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/panda/Documents/Agently-Daily-News-Collector/workflows/column_workflow.py", line 51, in pick_news_executor
    for pick_result in pick_results:
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/MainExecutor.py", line 266, in _exec_chunk_with_dep_core
    exec_res = chunk_executor(deps_dict, self.store)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/panda/Documents/Agently-Daily-News-Collector/workflows/main_workflow.py", line 58, in generate_columns_executor
    column_data = start_column_workflow(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/panda/Documents/Agently-Daily-News-Collector/workflows/column_workflow.py", line 151, in start
    column_workflow.start()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/Workflow.py", line 67, in start
    self.executor.start(runtime_data)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/MainExecutor.py", line 33, in start
    self._execute_main(entries)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/MainExecutor.py", line 70, in _execute_main
    self._execute_partial(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/MainExecutor.py", line 108, in _execute_partial
    child_executed = self._execute_single_chunk(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/MainExecutor.py", line 165, in _execute_single_chunk
    self._execute_single_chunk_core(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/MainExecutor.py", line 194, in _execute_single_chunk_core
    exec_value = self._exec_chunk_with_dep_core(chunk, single_dep_map)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/MainExecutor.py", line 270, in _exec_chunk_with_dep_core
    raise Exception(e)
Exception: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/panda/Documents/Agently-Daily-News-Collector/app.py", line 21, in <module>
    main_workflow.start(
  File "/Users/panda/Documents/Agently-Daily-News-Collector/workflows/main_workflow.py", line 109, in start
    main_workflow.start()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/Workflow.py", line 67, in start
    self.executor.start(runtime_data)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/MainExecutor.py", line 33, in start
    self._execute_main(entries)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/MainExecutor.py", line 70, in _execute_main
    self._execute_partial(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/MainExecutor.py", line 108, in _execute_partial
    child_executed = self._execute_single_chunk(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/MainExecutor.py", line 165, in _execute_single_chunk
    self._execute_single_chunk_core(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/MainExecutor.py", line 194, in _execute_single_chunk_core
    exec_value = self._exec_chunk_with_dep_core(chunk, single_dep_map)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/Agently/Workflow/MainExecutor.py", line 270, in _exec_chunk_with_dep_core
    raise Exception(e)
Exception: 'NoneType' object is not iterable
panda@localhost Agently-Daily-News-Collector %
```

**Comment by Maplemx** [comment]
It seems model ability related. Switch to other model and try again?

**Comment by PandaPan123** [comment]
替换了模型解决了问题，十分感谢回复
